logging.level.ru.yandex.practicum.filmorate: trace

#for some another port
#server.port: 8081

#for random port
#server.port: 0

spring:
  sql.init.mode: always
  datasource:
#    url: jdbc:h2:file:./db/filmorate
    url: jdbc:h2:mem:filmorate
    driverClassName: org.h2.Driver
    username: sa
#    password: password
  h2:
    console.enabled: true
    console.path: /h2-console
    console.settings.trace: false
    spring.h2.console.settings.web-allow-others: false